# where to put the log. base directory is home
log_directory: 'data/log'
log_link_directory: 'data'
log_link_name: 'winter.log'

filters:

        positions:
            1: 'dark'
            2: 'Y'
            3: 'J'
            4: 'Hs'
        encoder_positions:
            1: 0
            2: 22510
            3: 43745
            4: 65010

serial:

    #port: '/dev/tty.usbserial-AG0JG9J3'
    port: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AG0JG9J3-if00-port0'
    address: 1
    baud_rate: 9600

stepper_config:

    move_max_volt: 80
    encoder_ratio: 140056
    speed: 1000
    homing_steps: 100000
    max_encoder_err: 50
    overload_timeout: 100
    hold_current: 0
    timeout_secs: 80

state_update_dt: 0.2
reply_timeout: 0.2