# where to put the log. base directory is home
log_directory: 'data/log'
log_link_directory: 'data'
log_link_name: 'winter.log'

filters:

        positions:
            1: 'dark'
            2: 'Y'
            3: 'J'
            4: 'Hs'
        encoder_positions:
            1: 1000
            2: 2000
            3: 3000
            4: 4000

serial:

    port: '/dev/ttyUSB0'
    address: 1