#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 26 15:28:03 2021

skymodelBuilder.py

This file is part of wsp

# PURPOSE #
This module defines a skymodel builder object which has some useful functions for
creating a grid of points to use for creating a sky model using PWI4.

The idea is that an instance of this will be init'd by roboOperator which will
then do observations of the points from the lists generated by this object,
and then roboOperator will handle passing the data from this model object to 
the PWI4 interface using the telescope commands.


@author: nlourie
"""


