#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 26 15:28:03 2021

skymodelBuilder.py

This file is part of wsp

# PURPOSE #
This module defines a skymodel builder object which has some useful functions for
creating a grid of points to use for creating a sky model using PWI4.

The idea is that an instance of this will be init'd by roboOperator which will
then do observations of the points from the lists generated by this object,
and then roboOperator will handle passing the data from this model object to 
the PWI4 interface using the telescope commands.

This approach and many of these functions are adapted from Kevin Ivarsen
(Planewave) example: pwi4_build_model.py


@author: nlourie
"""


# system packages
import sys
import os
import numpy as np
import time
import signal
from PyQt5 import uic, QtCore, QtGui, QtWidgets
import Pyro5.client
import yaml

# add the wsp directory to the PATH
wsp_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(1, wsp_path)
print(f'control: wsp_path = {wsp_path}')


class SkymodelBuilder(object):
    '''
    An object to hold the functions needed to set up and execute the creation
    of a new sky model.
    
    Relies on Planewave's PWI4 interface, and uses Planewave's platesolve
    tools for astrometry
    '''
    
    def __init__(self):
        pass
    