# config file for WINTER


# telescope
telescope:
    host: "thor"
    port: 8220



# housekeeping

# define update times (ms)
daq_dt:
    fast: 100.0
    slow: 1000.0
    
write_dt: 1000.0    

# where to put the data. base directory is home
housekeeping_data_directory: 'data/rawdir'
housekeeping_data_link_directory: 'data'
housekeeping_data_link_name: 'dm.lnk'


# define housekeeping catagories to load in each mode
mode:
    instrument:
        -instrument
    telescope:
        -telescope
    observatory:
        -weather
        -telescope
        -site

# define telescope home position
telescope_home:
    alt_degs: 16.0
    az_degs: 290.0       

# define telemetry servers
telemetry_server:
    addr:  '198.202.125.214'
    port: 4698
    cmd: 'WEATHER_JSON'
    endchar: '}]'
    timeout: 0.01

command_server:
    addr: '198.202.125.142'
    port: 62000
    cmd: 'status?'
    endchar: '}'
    timeout: 0.01
    
# weather limits
weather_limits:
    TEMP_OUT: 
        MIN: -20
        MAX: 50
    TEMP_IN:
        MIN: -20
        MAX: 50
    RH_OUT:
        MIN: -100
        MAX: 100
    RH_IN:
        MIN: -100
        MAX: 100
    WIND_GUST:
        MIN: 0
        MAX: 35
    WIND_SPEED:
        MIN: 0
        MAX: 30
    DEWPOINT_IN:
        MIN: -100
        MAX: 100
    DEWPOINT_OUT:
        MIN: -100
        MAX: 100 
    # these are from clear dark skies:
    TRANSPARENCY:
        MIN: 3 # average
        MAX: 5 # transparent   
    SEEING:
        MIN: 3 # average
        MAX: 5 # excellent
    CLOUDS:
        MIN: 7 # 30pct covered
        MAX: 10 # CLEAR
    






# define fields. 
# Note: each rate must have a corresponding "daq_rate" as given above
fields:
#general:
    fcount:
        label: 'FastCount'
        units: None
        dtype: float64
        rate: fast
        var: 'index'
        
    scount:
        label: 'SlowCount'
        units: None
        dtype: float64
        rate: slow
        var: 'index'
#telescope
    site_latitude_degs:
        label: Latitude
        units: deg
        dtype: float64
        rate: fast
        var: telescope_status.site.latitude_degs
    site_longitude_degs:
        label: Longitude
        units: deg
        dtype: float64
        rate: fast
        var: telescope_status.site.longitude_degs
    site_height_meters:
        label: Height
        units: m
        dtype: float64
        rate: fast
        var: telescope_status.site.height_meters
    site_lmst_hours:
        label: LMST
        units: hours
        dtype: float64
        rate: fast
        var: telescope_status.site.lmst_hours
    
    mount_is_connected:
        label: 'MountConnected'
        units: None
        dtype: int64
        rate: fast
        var: telescope_status.mount.is_connected
    mount_geometry:
        label: Mode
        units: None
        dtype: int64
        rate: fast
        var: telescope_status.mount.geometry
    mount_ra_apparent_hours:
        label: RA
        units: hours
        dtype: float64
        rate: fast
        var: telescope_status.mount.ra_apparent_hours
    mount_dec_apparent_degs:
        label: DEC
        units: degs
        dtype: float64
        rate: fast
        var: telescope_status.mount.dec_apparent_degs
    mount_is_slewing:
        label: 'MountSlewing'
        units: None
        dtype: int64
        rate: fast
        var: 'telescope_status.mount.is_slewing'
    mount_az_deg:
        label: 'Az'
        units: 'deg'
        dtype: float64
        rate: fast
        var: 'telescope_status.mount.azimuth_degs'
    mount_alt_deg:
        label: 'Alt'
        units: 'deg'
        dtype: float64
        rate: fast
        var: 'telescope_status.mount.altitude_degs'
    mount_az_is_enabled:
        label: 'AzEnabled'
        units: None
        dtype: int
        rate: fast
        var: 'telescope_status.mount.axis0.is_enabled'
    mount_alt_is_enabled:
        label: 'AltEnabled'
        units: None
        dtype: int
        rate: fast
        var: 'telescope_status.mount.axis1.is_enabled'
#weather:
    #CDS (Clear Dark Skies)
    cds_cloud:
        label: 'CDS-Clouds'
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSCLOUD'
    cloud_min:
        label: 'Clouds-Min'
        units: None
        dtype: float64
        rate: slow
        var: 'weather.CLOUD_MIN'
    cloud_max:
        label: 'Clouds-Max'
        units: None
        dtype: float64
        rate: slow
        var: 'weather.CLOUD_MAX'
    # Palomar telemetry server: P48
    time_utc_p48:
        label: 'p48-time'
        units: 's'
        dtype: float64
        rate: slow
        var: weather.P48_UTC_timestamp
    ws_avg_threshold_p48:
        label: 'windspeed'
        units: 'mps'
        dtype: float64
        rate: slow
        var: weather.P48_Windspeed_Avg_Threshold
    ws_gust_threshold_p48:
        label: 'windspeed'
        units: 'mps'
        dtype: float64
        rate: slow
        var: weather.P48_Gust_Speed_Threshold
    time_alarm_p48:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: weather.P48_Alarm_Hold_Time
    time_remaining_hold_p48:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: weather.P48_Remaining_Hold_Time
    rh_threshold_outside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Remaining_Hold_Time
    rh_threshold_inside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_DewPt_Threshold
    wind_dir_current_p48:
        label: 'angle'
        units: 'degrees'
        dtype: float64
        rate: slow
        var: weather.P48_Wind_Dir_Current
    ws_current_p48:
        label: 'speed'
        units: 'm/s'
        dtype: float64
        rate: slow
        var: weather.P48_Windspeed_Current
    ws_avg_p48:
        label: 'speed'
        units: 'mps'
        dtype: float64
        rate: slow
        var: weather.P48_Windspeed_Average
    T_outside_air_p48:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Outside_Air_Temp
    rh_outside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Outside_Rel_Hum
    Tdp_outside_p48:
        label: 'DewPoint'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Outside_DewPt
    T_inside_air_p48:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_Air_Temp
    rh_inside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_Rel_Hum
    Tdp_inside_p48:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_DewPt
    wetness_p48:
        label: 'wetness'
        units: None
        dtype: int64
        rate: slow
        var: weather.P48_Wetness
    status_p48:
        label: 'ready'
        units: None
        dtype: int64
        rate: slow
        var: weather.P48_Weather_Status

        
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        