# config file for WINTER


# SCHEDULING
# location of the schedule files (base directory + this directory)
scheduleFile_directory: 'schedule/scheduleFiles'
scheduleFile_nightly_prefix: 'WINTER_NightlySchedule_'

# dither table
dither_file: 'config/dither_list.txt'

# telescope
telescope:
    host: "thor"
    port: 8220

# commanding (seconds)
cmd_timeout: 10.0
cmd_status_dt: 0.25

# housekeeping

# define update times (ms)
daq_dt:
    fast: 500.0
    slow: 500.0

# this will crash if this is not greater than or equal to the max daq_dt
write_dt: 500.0

# where to put the data. base directory is home
housekeeping_data_directory: 'data/rawdir'
housekeeping_data_link_directory: 'data'
housekeeping_data_link_name: 'dm.lnk'


# define housekeeping catagories to load in each mode
mode:
    instrument:
        -instrument
    telescope:
        -telescope
    observatory:
        -weather
        -telescope
        -site

# define telescope home position
telescope_home:
    alt_degs: 16.0
    az_degs: 290.0

# define telemetry servers
telemetry_server:
    addr:  '198.202.125.214'
    port: 4698
    cmd: 'WEATHER_JSON'
    endchar: '}]'
    timeout: 0.1

command_server:
    addr: '198.202.125.142'
    port: 62000
    cmd: 'status?'
    endchar: '}'
    timeout: 0.1

# dictionaries to interpret the status from the weather servers
# *NOTE*: it's best to use keys in quoatations to avoid the yaml loader converting them
#   for example, yaml loads key = YES as a boolean True value, but "YES" as a string
##P48
status_dict:
    P48_Wetness:
        'YES': 1
        'NO': 0
    P48_Weather_Status:
        'READY': 1
        'UNKNOWN': 0

    ## Palomar Command Server
    Dome_Status:
        'OFF': 0
        'STOPPED': 1
        'STOWED': 2
        'GO_TO': 3
        'FAULT': -20

    Shutter_Status:
        'OPENED': 10
        'OPENING': 5
        'CLOSED': -10
        'CLOSING': -5
        'STOPPED': 0
        'FAULT': -20

    Control_Status:
        'AVAILABLE': 0
        'REMOTE': 1
        'CONSOLE': 2
        'MANUAL': 3

    Close_Status:
        'READY': 1
        'NOT_READY': 0

    Weather_Status:
        'READY': 1
        'NOT_READY': 0



# weather limits
weather_limits:
    TEMP_OUT:
        MIN: -20
        MAX: 50
    TEMP_IN:
        MIN: -20
        MAX: 50
    RH_OUT:
        MIN: -100
        MAX: 100
    RH_IN:
        MIN: -100
        MAX: 100
    WIND_GUST:
        MIN: 0
        MAX: 35
    WIND_SPEED:
        MIN: 0
        MAX: 30
    DEWPOINT_IN:
        MIN: -100
        MAX: 100
    DEWPOINT_OUT:
        MIN: -100
        MAX: 100
    # these are from clear dark skies:
    TRANSPARENCY:
        MIN: 3 # average
        MAX: 5 # transparent
    SEEING:
        MIN: 3 # average
        MAX: 5 # excellent
    CLOUDS:
        MIN: 7 # 30pct covered
        MAX: 10 # CLEAR



# default value for housekeeping fields
default_value: -999



# define fields.
# Note: each rate must have a corresponding "daq_rate" as given above
fields:
#general:
    fcount:
        label: 'count'
        units: None
        dtype: float64
        rate: fast
        var: 'index'
    ftime:
        label: 'time'
        units: ctime
        dtype: float64
        rate: fast
        var: 'timestamp'

    scount:
        label: 'count'
        units: None
        dtype: float64
        rate: slow
        var: 'index'
    stime:
        label: 'time'
        units: ctime
        dtype: float64
        rate: slow
        var: 'timestamp'
#schedule
    az_scheduled:
        label: 'Az'
        units: deg
        dtype: float64
        rate: slow
        var: "schedule.scheduleExec.az_scheduled"
    alt_scheduled:
        label: 'Alt'
        units: deg
        dtype: float64
        rate: slow
        var: "schedule.scheduleExec.alt_scheduled"
    current_field_alt:
        label: 'Alt'
        units: deg
        dtype: float64
        rate: slow
        var: "schedule.scheduleExec.current_field_alt"
    current_field_az:
        label: 'Alt'
        units: deg
        dtype: float64
        rate: slow
        var: "schedule.scheduleExec.current_field_az"
#telescope
    site_latitude_degs:
        label: Latitude
        units: deg
        dtype: float64
        rate: fast
        var: telescope.state.site.latitude_degs
    site_longitude_degs:
        label: Longitude
        units: deg
        dtype: float64
        rate: fast
        var: telescope.state.site.longitude_degs
    site_height_meters:
        label: Height
        units: m
        dtype: float64
        rate: fast
        var: telescope.state.site.height_meters
    site_lmst_hours:
        label: LMST
        units: hours
        dtype: float64
        rate: fast
        var: telescope.state.site.lmst_hours

    mount_is_connected:
        label: 'MountConnected'
        units: None
        dtype: int64
        rate: fast
        var: telescope.state.mount.is_connected
    mount_geometry:
        label: Mode
        units: None
        dtype: int64
        rate: fast
        var: telescope.state.mount.geometry
    mount_ra_apparent_hours:
        label: RA
        units: hours
        dtype: float64
        rate: fast
        var: telescope.state.mount.ra_apparent_hours
    mount_dec_apparent_degs:
        label: DEC
        units: degs
        dtype: float64
        rate: fast
        var: telescope.state.mount.dec_apparent_degs
    mount_is_slewing:
        label: 'MountSlewing'
        units: None
        dtype: int64
        rate: fast
        var: 'telescope.state.mount.is_slewing'
    mount_az_deg:
        label: 'Az'
        units: 'deg'
        dtype: float64
        rate: fast
        var: 'telescope.state.mount.azimuth_degs'
    mount_alt_deg:
        label: 'Alt'
        units: 'deg'
        dtype: float64
        rate: fast
        var: 'telescope.state.mount.altitude_degs'
    mount_az_is_enabled:
        label: 'AzEnabled'
        units: None
        dtype: int
        rate: fast
        var: 'telescope.state.mount.axis0.is_enabled'
    mount_alt_is_enabled:
        label: 'AltEnabled'
        units: None
        dtype: int
        rate: fast
        var: 'telescope.state.mount.axis1.is_enabled'
    mount_az_dist_to_target:
        label: 'Dist'
        units: 'degs'
        dtype: float64
        rate: fast
        var: 'telescope.state.mount.axis0.dist_to_target_arcsec'
    mount_alt_dist_to_target:
        label: 'Dist'
        units: 'degs'
        dtype: float64
        rate: fast
        var: 'telescope.state.mount.axis1.dist_to_target_arcsec'
#weather:
    #CDS (Clear Dark Skies)
    cds_cloud_index:
        label: 'CloudIndex'
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSCLOUD'
    cds_trans_index:
        label: TransIndex
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSTRANS'
    cds_seeing_index:
        label: SeeingIndex
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSSEEING'
    cds_wind_index:
        label: WindIndex
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSWINDI'
    ws_cds_max:
        label: Speed
        units: mph
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSWINDMAX'
    ws_cds_min:
        label: Speed
        units: mph
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSWINDMIN'
    cds_rh_index:
        label: RHIndex
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSRHI'
    rh_cds_min:
        label: RH
        units: pct
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSRHMIN'
    rh_cds_max:
        label: RH
        units: pct
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSRHMAX'
    rh_cds_min:
        label: RH
        units: pct
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSRHMAX'
    cds_temp_index:
        label: TempIndex
        units: None
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSTEMPI'
    T_cds_min:
        label: T
        units: C
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSTEMPMIN'
    T_cds_max:
        label: T
        units: C
        dtype: float64
        rate: slow
        sys: weather
        var: 'weather.CDSTEMPMAX'
    cloud_min:
        label: 'Clouds-Min'
        units: None
        dtype: float64
        rate: slow
        var: 'weather.CLOUD_MIN'
    cloud_max:
        label: 'Clouds-Max'
        units: None
        dtype: float64
        rate: slow
        var: 'weather.CLOUD_MAX'
    # Palomar Command Server: PCS
    pcs_is_online:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.PCS_Online'
    time_utc_pcs:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: 'weather.PCS_UTC_timestamp'
    dome_az_deg:
        label: 'Az'
        units: 'deg'
        dtype: float64
        rate: slow
        var: 'weather.PCS_Dome_Azimuth'
    dome_status:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.PCS_Dome_Status_Num'
    dome_shutter_Status:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.PCS_Shutter_Status_Num'
    dome_control_status:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.PCS_Control_Status_Num'
    dome_close_status:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.PCS_Close_Status_Num'
    dome_weather_status:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.PCS_Weather_Status_Num'
    Tdp_outside_threshold_pcs:
        label: 'DewPoint'
        units: 'C'
        dtype: float64
        rate: slow
        var: 'weather.PCS_Outside_Dewpoint_Threshold'
    T_outside_pcs:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: 'weather.PCS_Outside_Temp'
    rh_outside_pcs:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: 'weather.PCS_Outside_RH'
    Tdp_outside_pcs:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: 'weather.PCS_Outside_Dewpoint'
    time_remaining_hold_pcs:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: 'weather.PCS_Weather_Hold_time'
    # Palomar telemetry server: P48
    p48_is_online:
        label: 'status'
        units: None
        dtype: int64
        rate: slow
        var: 'weather.P48_Online'
    time_utc_p48:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: weather.P48_UTC_timestamp
    ws_avg_threshold_p48:
        label: 'windspeed'
        units: 'mps'
        dtype: float64
        rate: slow
        var: weather.P48_Windspeed_Avg_Threshold
    ws_gust_threshold_p48:
        label: 'windspeed'
        units: 'mps'
        dtype: float64
        rate: slow
        var: weather.P48_Gust_Speed_Threshold
    time_alarm_p48:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: weather.P48_Alarm_Hold_Time
    time_remaining_hold_p48:
        label: 'time'
        units: 's'
        dtype: float64
        rate: slow
        var: weather.P48_Remaining_Hold_Time
    rh_threshold_outside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Remaining_Hold_Time
    rh_threshold_inside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_DewPt_Threshold
    wind_dir_current_p48:
        label: 'angle'
        units: 'degrees'
        dtype: float64
        rate: slow
        var: weather.P48_Wind_Dir_Current
    ws_current_p48:
        label: 'speed'
        units: 'm/s'
        dtype: float64
        rate: slow
        var: weather.P48_Windspeed_Current
    ws_avg_p48:
        label: 'speed'
        units: 'mps'
        dtype: float64
        rate: slow
        var: weather.P48_Windspeed_Average
    T_outside_air_p48:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Outside_Air_Temp
    rh_outside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Outside_Rel_Hum
    Tdp_outside_p48:
        label: 'DewPoint'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Outside_DewPt
    T_inside_air_p48:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_Air_Temp
    rh_inside_p48:
        label: 'RH'
        units: 'pct'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_Rel_Hum
    Tdp_inside_p48:
        label: 'T'
        units: 'C'
        dtype: float64
        rate: slow
        var: weather.P48_Inside_DewPt
    wetness_p48:
        label: 'wetness'
        units: None
        dtype: int64
        rate: slow
        var: weather.P48_Wetness_Num
    status_p48:
        label: 'ready'
        units: None
        dtype: int64
        rate: slow
        var: weather.P48_Weather_Status_Num
