# Focuser Loop Param

focus_loop_param:
	micron_interval: 5
	#filt_limits : {'u':[10000,10500], '1':[10000,10500],'3': [900,10400], 'r':[900,10400]}
	recent_path: '/data/tonight_images.lnk'
	file_type: '\*fits'
	
filt_limits:
	u:
		upper: 10400
		lower: 9000
	r:
		upper: 10500
		lower: 10000
