# Labjack setup config


### DEVICE INFORMATION ###
lj_type: "T7"
conn_type: 'ETHERNET'
address: "192.168.1.110"




### ANALOG INPUTS ###
# Can set for AIN0-14
ANALOG_INPUTS:
    AIN0:
        RESOLUTION_INDEX: 8 # 8 is the max for the T7
        NEGATIVE_CH: 199    # 199 is the default: single-ended measurement
        RANGE: 10       # the max voltage (ie sets the gain): can be 10, 1, 0.1, 0.01
        SETTLING_US: 0      # settling time in microseconds. 0 is automatic settling (recommended)
    
    AIN1:
        RANGE: 10
    
    AIN2:
        RANGE: 10
    AIN3:
        RANGE: 10
    AIN4:
        RANGE: 10
    AIN5:
        RANGE: 10
    AIN6:
        RANGE: 10
    AIN7:
        RANGE: 10
    AIN8:
        RANGE: 10
    AIN9:
        RANGE: 10
    AIN10:
        RANGE: 10
    AIN11:
        RANGE: 10
    AIN12:
        RANGE: 10
    AIN13:
        RANGE: 10
    AIN14:
    # this is the internal temperature sens
        RANGE: 10
#    AIN44444:
#        RANGE: 1

DIGITAL_COUNTERS:
    - DIO0
    - DIO1
#    - FIO1
#    - FIO2
#    - FIO3
#    - FIO4
#    - FIO5

### DIGITAL INPUTS/OUTPUTS ###
DIGITAL_INPUTS:
    - FIO6
    
DIGITAL_OUTPUTS:
    # output is zero or one
    FIO4:
        OUTPUT: 0
    FIO5:
        OUTPUT: 0
    FIO6:
        OUTPUT: 0
    
    
        
        
    
    