#power configuration file
# replaces the old configObject and .ini system

# the startup code is sent to the pdu on autostart=True
#    1 = turn on, 0 = turn off, 2 = do nothing

pdus:
    pdu1:
        pdu_number: 1
        ip: 192.168.1.31
        brand: 'Synaccess'
        model: 'SP-1001AE-01'
        outlets:
            1: Odin #'Callamp (2)'
            2: Freya #'Empty (1)'
            3: EMPTY #TelescopePDU #'PurgeFlow (2)'
            4: Sol #'Empty (1)'
            5: EMPTY #'Switch (1)'
            6: EMPTY #'Router (1)'
            7: PurgeFlow #'Empty (1)'
            8: FreyaBackup #'Empty (1)'
        startup: 11111121
    pdu2:
        pdu_number: 2
        ip: 192.168.1.32
        brand: 'Synaccess'
        model: 'SP-1001AE-01'
        outlets:
            1: Camera12V #'Camera12V (2)'
            2: FPAS #'FPAS (2)'
            3: SUMMERacc #'Empty (1)'
            4: SUMMERcam #'Empty (1)'
            5: WINTERacc #'Odin (1)'
            6: Callamp #'SUMMER (1)'
            7: EMPTY #'Thor (1)'
            8: EMPTY #'Freya (1)'
        startup: 22222111
    pdu3:
        pdu_number: 3
        ip: 192.168.1.33
        brand: 'Synaccess'
        model: 'NP-0201DX'
        outlets:
            1: Shutter
            2: Thor
        startup: 11

ups:
    ups1:
        ups_number: 1
        ip: 192.168.1.41
        brand: 'TrippLite'
        model: 'SU1500RTXLCDN'

