#power configuration file
# replaces the old configObject and .ini system

# the startup code is sent to the pdu on autostart=True
#    1 = turn on, 0 = turn off, 2 = do nothing

pdus:
    pdu1:
        pdu_number: 1
        ip: 192.168.1.14
        brand: 'Digital Loggers'
        outlets:
            1: 'Callamp'
            2: 'Empty'
            3: 'Empty'
            4: 'Empty'
            5: 'Switch'
            6: 'Router'
            7: 'Dead'
            8: 'Dead'
        startup: 21111111
    pdu2:
        pdu_number: 2
        ip: 192.168.1.75
        brand: 'Digital Loggers'
        outlets:
            1: 'Camera12V'
            2: 'FPAS'
            3: 'Empty'
            4: 'Empty'
            5: 'Odin'
            6: 'SUMMER'
            7: 'Thor'
            8: 'Freya'
        startup: 22111111
