#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May  6 15:31:32 2021

just a wrapper to rerun the daily scheduler


@author: winter
"""


import os
import sys
import yaml
from datetime import datetime

# add the wsp directory to the PATH
wsp_path = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(1, wsp_path)

# import the alert handler
from alerts import alert_handler
from utils import utils

# get the path for the scheduler
code_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
daily_scheduler_path = os.path.join(code_path, 'scheduler','daily_winter_scheduler')

# create the arguments
filepath = os.path.join(daily_scheduler_path,'run_winter_sim.py')
sky_config = os.path.join(daily_scheduler_path, 'sims', 'allsky_config.json')
night_config = os.path.join(daily_scheduler_path, 'config', 'tonight.cfg')

print('### RUNNING DAILY WINTER SCHEDULER ###')
print(f'wsp_path = {wsp_path}')
print(f'daily_scheduler_path = {daily_scheduler_path}')

cmd = f"python {filepath} '{sky_config}' '{night_config}'"

# where will the schedule file write to?
schedulefile_name = f'nightly_{utils.tonight()}.db'

# set up the alert system to post to slack
auth_config_file  = wsp_path + '/credentials/authentication.yaml'
user_config_file = wsp_path + '/credentials/alert_list.yaml'
alert_config_file = wsp_path + '/config/alert_config.yaml'

auth_config  = yaml.load(open(auth_config_file) , Loader = yaml.FullLoader)
user_config = yaml.load(open(user_config_file), Loader = yaml.FullLoader)
alert_config = yaml.load(open(alert_config_file), Loader = yaml.FullLoader)

alertHandler = alert_handler.AlertHandler(user_config, alert_config, auth_config)

msg = f"{datetime.now().strftime('%m/%d/%Y %H:%M')} running daily winter scheduler!"

alertHandler.slack_log(msg, group = None)
print(f'running command: {cmd}')






print('PRINTOUT FROM SCHEDULER:')

# run the daily scheduler!
os.system(cmd)




print(f'COMPLETE!')
msg = f'saved nightly schedule to ~/data/{schedulefile_name}'
alertHandler.slack_log(msg)